version: "2"
linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
