# golangci-lint v2.4.0用設定ファイル
# 注意: golangci-lint-action@v7はv2.x系のみサポート

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - golint
    - ineffassign
    - misspell
  disable:
    - funlen  # テスト関数が長いため無効化

issues:
  exclude-use-default: false
  exclude:
    # テストファイルのfunlenを除外
    - "Function '.+' is too long"