# golangci-lint configuration
# 詳細: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - prealloc

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  lll:
    line-length: 140
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/mzkmnk/ccforge
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
      - experimental
  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: true