linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - whitespace
    - gofmt

linters-settings:
  funlen:
    lines: 80  # テスト関数のため、制限を緩める
    statements: 60

issues:
  exclude-rules:
    # テストファイルではfunlenを無視
    - path: _test\.go
      linters:
        - funlen