# golangci-lint設定ファイル
# 注意: GitHub ActionsでGolangci-lint v2.4.0を使用しているため、
# 新しいバージョンの設定は使用できません

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - whitespace
    - gofmt

linters-settings:
  funlen:
    lines: 80
    statements: 60

issues:
  exclude-rules:
    # テストファイルではfunlenを無視
    - path: _test\.go
      linters:
        - funlen