version: "2"
linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - whitespace
formatters:
  enable:
    - gofmt
    - goimports