# GoReleaser configuration
# Documentation: https://goreleaser.com

project_name: ccforge

before:
  hooks:
    - go mod tidy

builds:
  - id: ccforge
    main: ./main.go
    binary: ccforge
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
  groups:
    - title: '🚀 Features'
      regexp: '^feat'
    - title: '🐛 Bug Fixes'
      regexp: '^fix'
    - title: '⚡ Performance'
      regexp: '^perf'
    - title: '♻️ Refactoring'
      regexp: '^refactor'
    - title: 'Others'

release:
  github:
    owner: mzkmnk
    name: ccforge
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
  header: |
    ## ccforge v{{.Version}}
    
    Claude Code TUI Application - Release {{.Date}}