name: CI

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    
    - name: Setup Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-stable-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-stable-
    
    - name: Download Dependencies
      run: go mod download
    
    - name: Format Check
      run: |
        go fmt ./...
        git diff --exit-code
    
    - name: Vet Check
      run: go vet ./...
    
    - name: Run Tests
      run: go test -v -race -coverprofile=coverage.out ./...
    
    - name: Coverage Report
      run: go tool cover -func=coverage.out
    
    - name: Build
      run: go build -v ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v7
      with:
        version: v2.4.0
        args: --timeout=5m

  security:
    name: Security Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    
    - name: Gosec Security Scan
      uses: securego/gosec@master
      with:
        args: ./...
    
    - name: Vulnerability Check
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck ./...