name: リリース

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: リリース
    runs-on: ubuntu-latest
    
    steps:
    - name: チェックアウト
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Go のセットアップ
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    
    - name: 依存関係のダウンロード
      run: go mod download
    
    - name: テスト実行
      run: go test -v ./...
    
    - name: GoReleaser のセットアップと実行
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-artifacts:
    name: ビルド成果物の作成
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: ccforge-linux-amd64
            build_name: ccforge
          - os: macos-latest
            artifact_name: ccforge-darwin-amd64
            build_name: ccforge
          - os: windows-latest
            artifact_name: ccforge-windows-amd64.exe
            build_name: ccforge.exe
    
    steps:
    - name: チェックアウト
      uses: actions/checkout@v4
    
    - name: Go のセットアップ
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    
    - name: 依存関係のダウンロード
      run: go mod download
    
    - name: ビルド
      run: |
        go build -v -o ${{ matrix.build_name }} .
    
    - name: アーティファクトのアップロード
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ matrix.build_name }}